# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBVI63V5PKqIYdao1-7C42DwRjY60Zzw
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer

df=pd.read_csv("cfs.csv")
df

x=df["feedback"]
y=df["sentiment"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

vectorizer=CountVectorizer()
x_train_vec=vectorizer.fit_transform(x_train)
x_test_vec=vectorizer.transform(x_test)

model=LogisticRegression()
model.fit(x_train_vec,y_train)

y_pred=model.predict(x_test_vec)

accuracy=accuracy_score(y_pred,y_test)
print(accuracy)

new_reviews = [
    "The product quality is amazing and delivery was very fast",
    "I am very unhappy with the service",
    "Great experience, I will definitely buy again",
    "The item arrived damaged and support was not helpful",
    "Excellent packaging and very good quality",
    "This is the worst purchase I have made",
    "Customer support solved my problem quickly",
    "The product is cheap and broke in two days",
    "Very satisfied with my order",
    "Terrible experience, I want my money back"
]

new_reviews_vec=vectorizer.transform(new_reviews)

new_pred=model.predict(new_reviews_vec)

print(new_pred)

